name: run-tests

'on':
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: shellcheck -s bash -S warning install-psm.bash psm.bash

  test-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash -x ./install-psm.bash
      - run: psm help

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: ./test.sh
